// <auto-generated />
namespace Fovea.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLikes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLikes));
        
        string IMigrationMetadata.Id
        {
            get { return "201711051928060_AddLikes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
